{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jodd",
    "module": "jodd-bean",
    "version": "5.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "dwj27welyje2jli43bdnq2ztmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jodd",
          "module": "jodd-core",
          "version": {
            "requires": "5.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "jodd-bean-5.1.6.jar",
          "url": "jodd-bean-5.1.6.jar",
          "size": 125529,
          "sha512": "2ed27a52de7ac6faba2f15fb46f8a6471acc396995760d4eb8da164fd7acd6af0b0d3347e57662755fa50684ab7ad3c8fd0354037f8ece98d339a003c5aadbc1",
          "sha256": "d07d805fe0d59b5d2dbc85d0ebfcf30f52d7fd5a3ff89ff4fbea1e46b1319705",
          "sha1": "5cbb398dda5c36908b123e98c373d3c1ef72f717",
          "md5": "7b176f6153dc408b072c9245b983071d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jodd",
          "module": "jodd-core",
          "version": {
            "requires": "5.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "jodd-bean-5.1.6.jar",
          "url": "jodd-bean-5.1.6.jar",
          "size": 125529,
          "sha512": "2ed27a52de7ac6faba2f15fb46f8a6471acc396995760d4eb8da164fd7acd6af0b0d3347e57662755fa50684ab7ad3c8fd0354037f8ece98d339a003c5aadbc1",
          "sha256": "d07d805fe0d59b5d2dbc85d0ebfcf30f52d7fd5a3ff89ff4fbea1e46b1319705",
          "sha1": "5cbb398dda5c36908b123e98c373d3c1ef72f717",
          "md5": "7b176f6153dc408b072c9245b983071d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-bean-5.1.6-javadoc.jar",
          "url": "jodd-bean-5.1.6-javadoc.jar",
          "size": 284160,
          "sha512": "f79caf70ddfa5e3e786a518bf13c59ac56769622e635fa6a68329ae909963b97a52c19b90e0ea5d20d636fd608d0d0528d886d57b33d31358f6b1defa31cb71e",
          "sha256": "a8a2e171b562fe9ee02885c16fafc1e7f8141e7e6c57f87cf6a1f6b90adf6700",
          "sha1": "ca19e72f42c09133b45bb3574b7dd06ca60943e6",
          "md5": "b4d9d52de3be6da800482b6d6ccae531"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-bean-5.1.6-sources.jar",
          "url": "jodd-bean-5.1.6-sources.jar",
          "size": 132077,
          "sha512": "fc8b0fe8e3191ed5a6e4900dfafb3be22b42752460c96b8922fe6e2686683111910cac7b4da5baf596cfe969db7455fa91717bbe5fbb4d8273c936fab08e98ec",
          "sha256": "961cff0114d349d3491293eea0c74a910b8676326c1af682f07e500782180160",
          "sha1": "ce65ceeb13b1dfe2dddde247357e5ffa15be3079",
          "md5": "63b94334307204e6005e50efad52c913"
        }
      ]
    }
  ]
}
