{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jodd",
    "module": "jodd-core",
    "version": "5.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "dwj27welyje2jli43bdnq2ztmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jodd-core-5.1.6.jar",
          "url": "jodd-core-5.1.6.jar",
          "size": 348094,
          "sha512": "984b2254683f7585e9330f8d369b8b1fe6bc03dd8d3cffeaaaf7167d48e45a743cb543758f1df0a8396fb68b3b7f88bdb1e492dc1650dc9bfed3605e6f3cb90a",
          "sha256": "4b504519263a98202480d3cf73562dff8245edc582350cc5f37d5965a0298122",
          "sha1": "7e3904364d0891b58a958c47336d35518084ddec",
          "md5": "d761922dcf939e52a5c092d2e8084b13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-core-5.1.6.jar",
          "url": "jodd-core-5.1.6.jar",
          "size": 348094,
          "sha512": "984b2254683f7585e9330f8d369b8b1fe6bc03dd8d3cffeaaaf7167d48e45a743cb543758f1df0a8396fb68b3b7f88bdb1e492dc1650dc9bfed3605e6f3cb90a",
          "sha256": "4b504519263a98202480d3cf73562dff8245edc582350cc5f37d5965a0298122",
          "sha1": "7e3904364d0891b58a958c47336d35518084ddec",
          "md5": "d761922dcf939e52a5c092d2e8084b13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-core-5.1.6-javadoc.jar",
          "url": "jodd-core-5.1.6-javadoc.jar",
          "size": 749980,
          "sha512": "98fc2f258476249735ddf9b8b961e7816c6b442ff54b399c1a51b32fca07b95003912ed22b0791ad317cfd1a783632740a213bc37938562b89901d0afea89738",
          "sha256": "9564c8a82969a1c6a8bd5f562f05c90ff9c23cdd0d664832aa05c97457b6e327",
          "sha1": "8fa3033f70122581e1b33d0782e2ef66bcd29eef",
          "md5": "20c84b942af5f610642f82cefa8c1c56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-core-5.1.6-sources.jar",
          "url": "jodd-core-5.1.6-sources.jar",
          "size": 344903,
          "sha512": "11b8b0abb2cb3f5271b58005383c3298f2b569fddd4f8e83115e4965c211ef6fc0c95e9af7761e5df5829bbed5887cec0abf57b25ff7e046b11e8f5c66b88901",
          "sha256": "2eb5a3af95296bc941767870bf5cb242ba7ee59a5eb0524c73e734578f6c6c16",
          "sha1": "88490d81766d79506165610184d42c56b560df98",
          "md5": "0fc0d9ae03ad1cbaadb98d71082eead9"
        }
      ]
    }
  ]
}
